name: AlgoMaster CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from your repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'  # Change this based on your .NET version

    # Restore NuGet dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the solution
    - name: Build the solution
      run: dotnet build --configuration Release --no-restore

    # Run NUnit tests
    - name: Run tests
      run: dotnet test --configuration Release --no-restore --verbosity normal
      # You can filter tests if needed using '--filter'